services:
  - type: web
    name: study-buddy-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_ACCESS_TOKEN_SECRECT
        generateValue: true
      - key: JWT_REFRESH_TOKEN_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "15"
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: "30"
      - key: COOKIE_SECURE
        value: "true"
      - key: RAG_API_KEY
        sync: false
      - key: RAG_EMBEDDING_MODEL
        value: gemini-embedding-001
      - key: RAG_CHAT_MODEL
        value: gemini-3.1-flash-lite
      - key: CLOUDNARY_CLOUD_NAME
        sync: false
      - key: CLOUDNARY_API_KEY
        sync: false
      - key: CLOUDNARY_API_SECRET
        sync: false
      - key: BRAVO_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GITHUB_CLIENT_ID
        value: ""
      - key: GITHUB_CLIENT_SECRET
        value: ""
      - key: GITHUB_REDIRECT_URI
        value: ""
