import os
from dotenv import load_dotenv

load_dotenv()

DB = os.getenv("DATABASE_URL")
REDIS_URL = os.getenv("UPSTASH_REDIS_REST_URL")
REDIS_TOKEN = os.getenv("UPSTASH_REDIS_REST_TOKEN")
BREVO_KEY = os.getenv("BRAVO_API_KEY")

JWT_ACCESS_TOKEN_SECRECT = os.getenv("JWT_ACCESS_TOKEN_SECRECT")
JWT_REFRESH_TOKEN_SECRET = os.getenv("JWT_REFRESH_TOKEN_SECRET")
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("JWT_ACCESS_TOKEN_EXPIRE_MINUTES")
JWT_REFRESH_TOKEN_EXPIRE_DAYS = os.getenv("JWT_REFRESH_TOKEN_EXPIRE_DAYS")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
