import os
from dotenv import load_dotenv

load_dotenv()

DB = os.getenv("DATABASE_URL")
REDIS_URL = os.getenv("UPSTASH_REDIS_REST_URL")
REDIS_TOKEN = os.getenv("UPSTASH_REDIS_REST_TOKEN")
BREVO_KEY = os.getenv("BRAVO_API_KEY")

JWT_ACCESS_TOKEN_SECRECT = os.getenv("JWT_ACCESS_TOKEN_SECRECT")
JWT_REFRESH_TOKEN_SECRET = os.getenv("JWT_REFRESH_TOKEN_SECRET")
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("JWT_ACCESS_TOKEN_EXPIRE_MINUTES")
JWT_REFRESH_TOKEN_EXPIRE_DAYS = os.getenv("JWT_REFRESH_TOKEN_EXPIRE_DAYS")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")
GOOGLE_AUTH_URI = os.getenv("GOOGLE_AUTH_URI")
GOOGLE_TOKEN_URI = os.getenv("GOOGLE_TOKEN_URI")
GOOGLE_PROVIDER_URI = os.getenv("GOOGLE_PROVIDER_URI")


GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")
GITHUB_REDIRECT_URI = os.getenv("GITHUB_REDIRECT_URI")

GITHUB_AUTH_URI = os.getenv("GITHUB_AUTH_URI")
GITHUB_TOKEN_URI = os.getenv("GITHUB_TOKEN_URI")
GITHUB_USER_URI = os.getenv("GITHUB_USER_URI")
GITHUB_USER_EMAILS_URI = os.getenv("GITHUB_USER_EMAILS_URI")
FRONT_END_URL = os.getenv("FRONTEND_URL")

REDIS_URL = os.getenv("REDIS_URL")
